name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - 5.0.100
        arango: 
          - "arangodb:3.6.8"
          - "arangodb:3.7.3"
          - "arangodb/enterprise:3.7.3"
        topology:
          - single
          - cluster

    steps:
    - uses: actions/checkout@v2
    
    - name: chmod
      run: find ./docker -name '*.sh' | xargs chmod +x
      
    - name: arango
      run: ./docker/start_db_${{ matrix.topology }}_retry_fail.sh ${{ matrix.arango }}
      env:
        ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
    
    - name: dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: build
      run: dotnet build --configuration Release
      
    - name: test
      run: dotnet test --configuration Release
      env:
        ARANGODB_CONNECTION: "Server=http://172.28.3.1:8529;Realm=CI-{UUID};User=root;Password=test;"
