name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - 8.x
        arango: 
#          - "arangodb:3.11"
          - "arangodb:latest"
#          - "arangodb/enterprise:3.9"
        topology:
          - single
#          - cluster

    steps:
    - uses: actions/checkout@v4

    - name: dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: build
      run: dotnet build --configuration Release
      
    - name: test
      run: dotnet test --configuration Release
      env:
        ARANGODB_VERSION: ${{ matrix.arango }}
        ARANGODB_TOPOLOGY: ${{ matrix.topology }}
